### ISSUE TITLE
Multiple configurations of pretested integration in pipelines and other job types can cause a problem for the publisher (changes not pushed)

### ISSUE THREAD

**Issue by MadsNielsen** [Praqma/pretested-integration-plugin#105]

**Comment by buep** [comment]
By design the pretested integration process is only to be used with one SCM at the time, so you're not supposed to try to integrate changes from more than one repository at the time.

This was an initial decision when creating the plugin, as we will never be able to ensure an atomic integration of several repositories at the time would succeed, so we will not try.

So there can only be one configuration of the pretested integration plugin in a Jenkins job.
Any Jenkins job do allow to configure multiple SCM, using either pipelines, MultiSCM plugin + freestyle job, or plain ordinary freestyle jobs with more than one git repository configured in the SCM.
We not able to check if this is the situation in a persistent matter for such jobs, so when a user configured the job against our recommendations the publisher where we push the changes to the integration branch can fail.

To protect against we have some build action data added in the scm part of our plugin, while the post-build part of the plugin then checks if there are several and only allow one.

It is related to changes done in #75.

**Comment by MadsNielsen** [comment]
Fail if more than 1 pretested integration happened during build.

**Comment by buep** [comment]
added inline comment to the commit.

Good we a code comment as well to explain it is only relevant for pipeline.
