### ISSUE TITLE
PiP pipeline Multibranch compliant?

### ISSUE THREAD

**Issue by sofusalbertsen** [Praqma/pretested-integration-plugin#85]
After a talk with @groenborg, I seem to get the idea that the new version does not support pipeline multibranch, but only singlebranch pipelines?
More info on the plugin here 
https://wiki.jenkins.io/display/JENKINS/Pipeline+Multibranch+Plugin
Can @buep confirm this?

**Comment by buep** [comment]
I can't confirm it because there is not deliberate decision around it. We will support you can use scripted, declarative and job dsl to describe your jobs. 
Further that the pretested integration functionality is now there as a git extension instead of a build wrapper.

I don't know what multibranch pipeline requires of special job configurations, but I don't see why it shouldn't work? Any idea what you expect is not working?

Will you try it?

**Comment by MadsNielsen** [comment]
Would be coole if you could try with it @sofusalbertsen 

Mulltibranch operates by creating a full pipeline for every branch in your repository, if the repository has a JENKINSFILE you'll get a pipeline in Jenkins (Correct me if im wrong here!). 

The JENKINSFILE is interpreted *before* integration of the ready branch to your integration branch, so if you've done changes in the JENKINSFILE on your ready branch, the pipeline you're execution is not the result of the merge with the integration branch. 

So...if your JENKINSFILES are the same it will work as expected...we think :)

**Comment by buep** [comment]
Thanks Mads for that clarification. The problem, which some might see once a while, related to #59.

**Comment by sofusalbertsen** [comment]
Closing this one, as I think it actually works.
We do know what integration branch we want to integrate with, and we can find out what branch triggered us, if not anything else, then by the script NT have made.
Could be done more elegant, if the plugin actually did this, but it's not a showstopper.
