### ISSUE TITLE
Fix workspace resolver

### ISSUE THREAD

**Issue by groenborg** [Praqma/pretested-integration-plugin#94]
There are two failing tests related to sum not being able to resolve the git workspace, if you have navigated into subdirectories. These issues have occurred  before and have been fixed in these two issues: 
- https://issues.jenkins-ci.org/browse/JENKINS-25545
- https://issues.jenkins-ci.org/browse/JENKINS-25445

After we removed the build wrapper, the error occurred again, but this time it does not look like we can resolve it as before, since we relied on build wrapper specific methods. The error also happens in the post checkout step.

**Comment by groenborg** [comment]
Any idea how to solve this @MadsNielsen

**Comment by MadsNielsen** [comment]
I'd take a look at the decorateRevison to buld method @groenborg. 

You can check if a specific extension is installed: 

`hudson.plugins.git.extensions.impl.RelativeTargetDirectory`

You ought to be able to deduce something from that one. It's the moment you create our git client that it's important.

**Comment by MadsNielsen** [comment]
I did a bit a research on this. 

For one, in pipeline the jenkins core team is suggesting to hide the 'Checkout to relative directory': https://issues.jenkins-ci.org/browse/JENKINS-43052

The issue is that in pipeline, you control this with the `dir(...)` command:

```
dir('some-subdir' ) {
  checkout scm
}
```
Jesse Glick is suggesting the author to hide this particular SCM extension for Pipeline jobs.

So, the bug is this: We need to pass the correct Workspace to the `perform(..)` method in the postbuild step for FreeStyle jobs we can use the getWorkspace method from the RelativeTargetDirectory extension. 

https://github.com/Praqma/pretested-integration-plugin/blob/3c2178ca2da29970d5e46a073b785a26aa91ff07/src/main/java/org/jenkinsci/plugins/pretestedintegration/PretestedIntegrationPostCheckout.java#L95-L104

In the above case, the workspace is passed in wrongly for freestyle jobs. 

Deliverables:

1) Implement fix for FreeStyle jobs that makes current test pass
2) Implement a test for Pipeline using the `dir(...)` syntax.
