### ISSUE TITLE
Write a warning to the user when adding a post-build step in a job type we do not support

### ISSUE THREAD

**Issue by buep** [Praqma/pretested-integration-plugin#97]
With version 3.x where the plugin works as a git scm extension, we're compatible with a lot more job types.

At least we expect so, but we haven't test it fully. So the job types we don't believe we have enough testing for we should report a  warning to the user about we haven't tested with the job type thoroughly but it might work.

I would prefer it to be reported in the UI when making jobs through the UI and adding the post-build step.
When that is not the case I propose to write a warning to the build console when running the post-build step.

This issue stems from #9 so please read the comments there before working on this issue to get the background.

**Comment by MadsNielsen** [comment]
To summerize we only really have 4 relevant job types.

1. FreeStyle Job
2. Pipeline Job
3. Matrix Job
4. MultiJob Job
5. Maven Job
6. BuildFlow Job (old pipeline job)

_1,2,5 are fully supported._ 
_3_ is fully supported, if we make sure to only push changes in the parent job and avoid doing it in child jobs. Ask @bicschneider 
The only wildcard is 4 and 6. We need to implement it for those job types.

Research: How can you check if the item you're configuring is a particular type? For this we need to implement a doCheck(...) method on our configuration object. Can you statically check this when the config page is loaded if so that would be a solution?

**Comment by buep** [comment]
> The only wildcard is 4 and 6. We need to implement it for those job types.
We will not test these, nor consider supporting them. 

Thus the plugin needs to write a warning in this case.

3 will be handled in our documentation.
